frame1 :-
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
nl.

frame2 :-
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.............XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
nl.

frame3 :-
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('.......................................................................'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
nl.

frame4 :-
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
nl.

frame5 :-
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
nl.

frame6 :-
write('XXXXXXXXXXXXXXXXXXXXXXXXXX...................XXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXX...................XXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXX...................XXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXX...................XXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXX...................XXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXX...................XXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXX...................XXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXX...................XXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXX...................XXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXX...................XXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXX...................XXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXX...................XXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXX...................XXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
write('XXXXXXXXXXXXXXXXXXXXXXXXXX...................XXXXXXXXXXXXXXXXXXXXXXXXXX'), nl,
nl.

frame7 :-
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
write('.......................................................................'), nl,
nl.

frame8 :-
write('                                                                       '), nl,
write('                          .&dkl`,ivne._                                '), nl,
write('                          sRfkgvc+rsnmGBND.                            '), nl,
write('                        aHBNLbni+.irumLGNMms                           '), nl,
write('                        NRIr`\'+dLKNMFb`\'iNQr                           '), nl,
write('                       `ANWM7    `+lM0.  `\'^Kl                         '), nl,
write('                       iNWL*_;=e.     Y._,_ ON                         '), nl,
write('                       aRNm   _.l,    j^ _` Bq,                        '), nl,
write('                       eNL:,l=N0`.   ls`N0> ibK                        '), nl,
write('                       XHZu!       _(c      kPBN                       '), nl,
write('                        \'CD   .     `      tK7KX                       '), nl,
write('                          \'f     _&zrc_.  .Y                           '), nl,
write('     ,                      v,   `ta.="  ,V                            '), nl,
write('    7q. 6%                   ^l     =   .r                             '), nl,
write('    f\'noib. +                `d+   .._a7                     t         '), nl,
write('    k+RD6 L.dr                h\'  `*+iPb                  .f adI`      '), nl,
write('    dj+Ggr 4NJb            .,dT     `\'KJc                 _ir+4b .     '), nl,
write('      `cl^ ._ tk.   .,&;:rf"t&;       \'yIKbr;.         dp` luhrZti     '), nl,
write('         `~.  ^_T `ysf\'      " n,     7     *lkr,.   i7k._m.JKiV"      '), nl,
write('            J  .H dY   `"-              ._``    "VK,4=   . Kdj`        '), nl,
write('            K   K B               -s&.            eJ+  .ys7^`          '), nl,
write('            T   lLj      /                    \\    (C\' .4              '), nl,
write('            P   \'y      |                     |   +j  7                '), nl,
write('                                                                       '), nl,
nl.

frame9 :-
write('                                                                       '), nl,
write('                          .&dkl`,ivne._                                '), nl,
write('                          sRfkgvc+rsnmGBND.                            '), nl,
write('                        aHBNLbni+.irumLGNMms                           '), nl,
write('                        NRIr`\'+dLKNMFb`\'iNQr                           '), nl,
write('                       `ANWM7    `+lM0.  `\'^Kl                         '), nl,
write('                       iNWL*                ON                         '), nl,
write('                       aRNm OOoOO     OOoOO Bq,                        '), nl,
write('                       eNL:,                ibK                        '), nl,
write('                       XHZu!       _(c      kPBN                       '), nl,
write('                        \'CD   .     `      tK7KX                       '), nl,
write('                          \'f     VIIIIIV  .Y                           '), nl,
write('     ,                      v,           ,V                            '), nl,
write('    7q. 6%                   ^l     =   .r                             '), nl,
write('    f\'noib. +                `d+   .._a7                     t         '), nl,
write('    k+RD6 L.dr                h\'  `*+iPb                  .f adI`      '), nl,
write('    dj+Ggr 4NJb            .,dT     `\'KJc                 _ir+4b .     '), nl,
write('      `cl^ ._ tk.   .,&;:rf"t&;       \'yIKbr;.         dp` luhrZti     '), nl,
write('         `~.  ^_T `ysf\'      " n,     7     *lkr,.   i7k._m.JKiV"      '), nl,
write('            J  .H dY   `"-              ._``    "VK,4=   . Kdj`        '), nl,
write('            K   K B               -s&.            eJ+  .ys7^`          '), nl,
write('            T   lLj      /                    \\    (C\' .4              '), nl,
write('            P   \'y      |                     |   +j  7                '), nl,
write('                                                                       '), nl,
nl.

frame10 :-
write('                                                                       '), nl,
write('                          .&dkl`,ivne._                                '), nl,
write('                          sRfkgvc+rsnmGBND.                            '), nl,
write('                        aHBNLbni+.irumLGNMms                           '), nl,
write('                        NRIr`\'+dLKNMFb`\'iNQr                           '), nl,
write('                       `ANWM7    `+lM0.  `\'^Kl                         '), nl,
write('                       iNWL*OOoOO     OOoOO ON                         '), nl,
write('                       aRNm oXXXo     oXXXo Bq,                        '), nl,
write('                       eNL:,OOoOO     OOoOO ibK                        '), nl,
write('                       XHZu!       _(c      kPBN                       '), nl,
write('                        \'CD   .     `      tK7KX                       '), nl,
write('                          \'f     VIIIIIV  .Y                           '), nl,
write('     ,                      v,    V___V  ,V                            '), nl,
write('    7q. 6%                   ^l     =   .r                             '), nl,
write('    f\'noib. +                `d+   .._a7                     t         '), nl,
write('    k+RD6 L.dr                h\'  `*+iPb                  .f adI`      '), nl,
write('    dj+Ggr 4NJb            .,dT     `\'KJc                 _ir+4b .     '), nl,
write('      `cl^ ._ tk.   .,&;:rf"t&;       \'yIKbr;.         dp` luhrZti     '), nl,
write('         `~.  ^_T `ysf\'      " n,     7     *lkr,.   i7k._m.JKiV"      '), nl,
write('            J  .H dY   `"-              ._``    "VK,4=   . Kdj`        '), nl,
write('            K   K B               -s&.            eJ+  .ys7^`          '), nl,
write('            T   lLj      /                    \\    (C\' .4              '), nl,
write('            P   \'y      |                     |   +j  7                '), nl,
write('                                                                       '), nl,
nl.

frame11 :-
write('                                                                       '), nl,
write('                          .&dkl`,ivne._                                '), nl,
write('                          sRfkgvc+rsnmGBND.                            '), nl,
write('                        aHBNLbni+.irumLGNMms                           '), nl,
write('                        NRIr`\'+dLKNMFb`\'iNQr                           '), nl,
write('                       `ANWM7    `+lM0.  `\'^Kl                         '), nl,
write('                       iNWL* OoO       OoO  ON                         '), nl,
write('                       aRNm o666o     o666o Bq,                        '), nl,
write('                       eNL:, OoO       OoO  ibK                        '), nl,
write('                       XHZu!       _(c      kPBN                       '), nl,
write('                        \'CD   .     `      tK7KX                       '), nl,
write('                          \'f      n---n   .Y                          '), nl,
write('     ,                      v,   M     M ,V                           '), nl,
write('    7q. 6%                   ^l     =   .r                             '), nl,
write('    f\'noib. +                `d+   .._a7                     t         '), nl,
write('    k+RD6 L.dr                h\'  `*+iPb                  .f adI`      '), nl,
write('    dj+Ggr 4NJb            .,dT     `\'KJc                 _ir+4b .     '), nl,
write('      `cl^ ._ tk.   .,&;:rf"t&;       \'yIKbr;.         dp` luhrZti     '), nl,
write('         `~.  ^_T `ysf\'      " n,     7     *lkr,.   i7k._m.JKiV"      '), nl,
write('            J  .H dY   `"-              ._``    "VK,4=   . Kdj`        '), nl,
write('            K   K B               -s&.            eJ+  .ys7^`          '), nl,
write('            T   lLj      /                    \\    (C\' .4              '), nl,
write('            P   \'y      |                     |   +j  7                '), nl,
write('                                                                       '), nl,
nl.

animateFront :- (shell('clear'); 1=1), frame1, sleep(0.1), 
                (shell('clear'); 1=1), frame2, sleep(0.1), 
                (shell('clear'); 1=1), frame3, sleep(0.1), 
                (shell('clear'); 1=1), frame4, sleep(0.1), 
                (shell('clear'); 1=1), frame5, sleep(0.1),
                (shell('clear'); 1=1), frame6, sleep(0.1), 
                (shell('clear'); 1=1), frame7, sleep(0.1), 
                (shell('clear'); 1=1), frame8, sleep(0.1), 
                (shell('clear'); 1=1), frame9, sleep(0.2), 
                (shell('clear'); 1=1), frame8, sleep(0.2), 
                (shell('clear'); 1=1), frame9, sleep(0.2), 
                (shell('clear'); 1=1), frame8, sleep(0.1).


animateAttack :- (shell('clear'); 1=1), frame1, sleep(0.1), 
                (shell('clear'); 1=1), frame2, sleep(0.1), 
                (shell('clear'); 1=1), frame3, sleep(0.1), 
                (shell('clear'); 1=1), frame4, sleep(0.1), 
                (shell('clear'); 1=1), frame5, sleep(0.1),
                (shell('clear'); 1=1), frame6, sleep(0.1), 
                (shell('clear'); 1=1), frame7, sleep(0.1), 
                (shell('clear'); 1=1), frame8, sleep(0.1), 
                (shell('clear'); 1=1), frame9, sleep(0.2), 
                (shell('clear'); 1=1), frame10, sleep(0.2), 
                (shell('clear'); 1=1), frame9, sleep(0.2), 
                (shell('clear'); 1=1), frame8, sleep(0.2), 
                (shell('clear'); 1=1), frame9, sleep(0.2), 
                (shell('clear'); 1=1), frame10, sleep(0.2), 
                (shell('clear'); 1=1), frame9, sleep(0.2), 
                (shell('clear'); 1=1), frame8, sleep(0.1).

animateSAttack :- (shell('clear'); 1=1), frame1, sleep(0.1), 
                  (shell('clear'); 1=1), frame2, sleep(0.1), 
                  (shell('clear'); 1=1), frame3, sleep(0.1), 
                  (shell('clear'); 1=1), frame4, sleep(0.1), 
                  (shell('clear'); 1=1), frame5, sleep(0.1),
                  (shell('clear'); 1=1), frame6, sleep(0.1), 
                  (shell('clear'); 1=1), frame7, sleep(0.1), 
                  (shell('clear'); 1=1), frame8, sleep(0.1), 
                  (shell('clear'); 1=1), frame9, sleep(0.2), 
                  (shell('clear'); 1=1), frame11, sleep(0.2), 
                  (shell('clear'); 1=1), frame9, sleep(0.2), 
                  (shell('clear'); 1=1), frame8, sleep(0.2),  
                  (shell('clear'); 1=1), frame9, sleep(0.2), 
                  (shell('clear'); 1=1), frame11, sleep(0.2), 
                  (shell('clear'); 1=1), frame9, sleep(0.2), 
                  (shell('clear'); 1=1), frame8, sleep(0.1).